// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddProject():Promise<string>;

export function GetState():Promise<main.AppState>;

export function HideWindow():Promise<void>;

export function KillAll():Promise<void>;

export function KillCommand(arg1:string):Promise<void>;

export function RemoveCommand(arg1:string,arg2:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function SelectProject(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function StartAll():Promise<void>;

export function StartCommand(arg1:string):Promise<void>;
