// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCommand'](arg1, arg2, arg3);
}

export function AddProject() {
  return window['go']['main']['App']['AddProject']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function KillAll() {
  return window['go']['main']['App']['KillAll']();
}

export function KillCommand(arg1) {
  return window['go']['main']['App']['KillCommand'](arg1);
}

export function RemoveCommand(arg1, arg2) {
  return window['go']['main']['App']['RemoveCommand'](arg1, arg2);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}

export function StartCommand(arg1) {
  return window['go']['main']['App']['StartCommand'](arg1);
}
